2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 59.57.149.60:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 180.122.180.236:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.152.91.1:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 106.92.96.203:8118
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 175.44.108.113:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 171.35.162.52:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.16.26:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.22.243:9999
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 190.206.123.169:8080
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.215.247.97:9999
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 47.98.56.88:80
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.20.227:9999
2019-12-12 12:20:16 connectionpool.py [line:437] DEBUG: http://47.98.56.88:80 "GET http://httpbin.org/get HTTP/1.1" 403 597
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 122.2.37.38:34817
2019-12-12 12:20:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.195.170.175:9999
2019-12-12 12:20:16 connectionpool.py [line:437] DEBUG: http://59.57.149.60:9999 "GET http://httpbin.org/get HTTP/1.1" 200 343
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:17 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.176.210:3000
2019-12-12 12:20:18 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 39.108.230.67:8080
2019-12-12 12:20:19 connectionpool.py [line:437] DEBUG: http://39.108.230.67:8080 "GET http://httpbin.org/get HTTP/1.1" 200 298
2019-12-12 12:20:19 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:20 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 218.2.226.42:80
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:21 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.209.131.3:8080
2019-12-12 12:20:22 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:23 connectionpool.py [line:437] DEBUG: http://218.2.226.42:80 "GET http://httpbin.org/get HTTP/1.1" 200 286
2019-12-12 12:20:23 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 1.199.31.25:9999
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.44.122.85:8080
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 81.190.208.52:35922
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.92.18.179:8080
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.45.172.224:8118
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.220.145.3:80
2019-12-12 12:20:26 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 78.62.214.242:60678
2019-12-12 12:20:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:27 connectionpool.py [line:437] DEBUG: http://183.220.145.3:80 "GET http://httpbin.org/get HTTP/1.1" 200 352
2019-12-12 12:20:27 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:27 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.245.198.101:8080
2019-12-12 12:20:28 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 85.196.147.146:31784
2019-12-12 12:20:29 connectionpool.py [line:437] DEBUG: http://103.245.198.101:8080 "GET http://httpbin.org/get HTTP/1.1" 200 497
2019-12-12 12:20:29 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:30 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:31 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:31 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:31 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:31 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 81.24.91.231:41258
2019-12-12 12:20:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.242.191:9999
2019-12-12 12:20:32 connectionpool.py [line:437] DEBUG: http://81.190.208.52:35922 "GET http://httpbin.org/get HTTP/1.1" 200 314
2019-12-12 12:20:32 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 219.239.142.253:3128
2019-12-12 12:20:33 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.243.126:9999
2019-12-12 12:20:33 connectionpool.py [line:437] DEBUG: http://219.239.142.253:3128 "GET http://httpbin.org/get HTTP/1.1" 200 516
2019-12-12 12:20:33 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:35 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 212.156.55.34:8080
2019-12-12 12:20:36 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 185.44.229.227:34930
2019-12-12 12:20:36 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.92.194.49:8118
2019-12-12 12:20:36 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:36 connectionpool.py [line:437] DEBUG: http://182.92.194.49:8118 "GET http://httpbin.org/get HTTP/1.1" 200 292
2019-12-12 12:20:36 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:37 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 218.59.193.14:43554
2019-12-12 12:20:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:37 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 203.150.172.151:8080
2019-12-12 12:20:38 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 189.124.91.185:8080
2019-12-12 12:20:38 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:39 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.232.39.55:8080
2019-12-12 12:20:41 connectionpool.py [line:437] DEBUG: http://185.44.229.227:34930 "GET http://httpbin.org/get HTTP/1.1" 200 304
2019-12-12 12:20:41 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 118.173.233.31:59669
2019-12-12 12:20:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.168.252.49:8080
2019-12-12 12:20:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.99.0.176:9999
2019-12-12 12:20:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.235.99.114:30865
2019-12-12 12:20:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:43 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:43 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 74.113.173.78:47208
2019-12-12 12:20:44 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:45 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.46.207.215:9999
2019-12-12 12:20:46 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 118.96.173.115:8080
2019-12-12 12:20:46 connectionpool.py [line:437] DEBUG: http://176.235.99.114:30865 "GET http://httpbin.org/get HTTP/1.1" 200 473
2019-12-12 12:20:46 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:46 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:47 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 168.205.92.94:8080
2019-12-12 12:20:47 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 134.35.198.130:8080
2019-12-12 12:20:48 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:49 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.36.111.9:61102
2019-12-12 12:20:50 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:50 connectionpool.py [line:437] DEBUG: http://118.96.173.115:8080 "GET http://httpbin.org/get HTTP/1.1" 200 482
2019-12-12 12:20:50 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:51 connectionpool.py [line:437] DEBUG: http://168.205.92.94:8080 "GET http://httpbin.org/get HTTP/1.1" 200 351
2019-12-12 12:20:51 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 125.25.32.173:8080
2019-12-12 12:20:51 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:51 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:51 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.17.207:9999
2019-12-12 12:20:51 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 171.35.166.183:9999
2019-12-12 12:20:52 connectionpool.py [line:437] DEBUG: http://223.198.17.207:9999 "GET http://httpbin.org/get HTTP/1.1" 200 341
2019-12-12 12:20:52 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:52 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:52 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 119.179.196.116:9999
2019-12-12 12:20:52 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:53 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.20.72:9999
2019-12-12 12:20:53 connectionpool.py [line:437] DEBUG: http://223.198.20.72:9999 "GET http://httpbin.org/get HTTP/1.1" 403 3765
2019-12-12 12:20:53 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:54 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 120.55.69.176:8080
2019-12-12 12:20:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 190.5.118.42:8080
2019-12-12 12:20:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.239.151.79:9999
2019-12-12 12:20:55 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 102.141.197.17:8080
2019-12-12 12:20:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 112.111.77.17:9999
2019-12-12 12:20:56 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.21.239:9999
2019-12-12 12:20:56 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:56 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.85.166.189:8118
2019-12-12 12:20:56 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:57 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 195.178.33.86:8080
2019-12-12 12:20:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:57 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 43.225.67.35:53905
2019-12-12 12:20:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.176.180:3000
2019-12-12 12:20:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:20:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.169.125.180:9999
2019-12-12 12:21:00 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:01 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.6.227.28:8080
2019-12-12 12:21:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.166.163.178:9999
2019-12-12 12:21:02 connectionpool.py [line:437] DEBUG: http://195.178.33.86:8080 "GET http://httpbin.org/get HTTP/1.1" 200 542
2019-12-12 12:21:02 connectionpool.py [line:437] DEBUG: http://183.166.163.178:9999 "GET http://httpbin.org/get HTTP/1.1" 403 3749
2019-12-12 12:21:02 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:03 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:03 connectionpool.py [line:437] DEBUG: http://190.5.118.42:8080 "GET http://httpbin.org/get HTTP/1.1" 200 496
2019-12-12 12:21:03 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:03 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.63.205.248:30616
2019-12-12 12:21:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:05 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 61.54.6.21:8118
2019-12-12 12:21:05 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.121.65.144:9999
2019-12-12 12:21:05 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.88.63.68:8080
2019-12-12 12:21:06 connectionpool.py [line:437] DEBUG: http://183.88.63.68:8080 "GET http://httpbin.org/get HTTP/1.1" 200 487
2019-12-12 12:21:06 connectionpool.py [line:437] DEBUG: http://61.54.6.21:8118 "GET http://httpbin.org/get HTTP/1.1" 200 None
2019-12-12 12:21:06 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:06 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:07 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:07 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:07 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 14.207.56.175:8080
2019-12-12 12:21:08 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.89.44.235:8080
2019-12-12 12:21:08 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:09 connectionpool.py [line:437] DEBUG: http://14.207.56.175:8080 "GET http://httpbin.org/get HTTP/1.1" 200 530
2019-12-12 12:21:09 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:09 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.92.212.65:43399
2019-12-12 12:21:09 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.252.67.206:8080
2019-12-12 12:21:09 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 181.236.247.136:58310
2019-12-12 12:21:10 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:11 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.169.168.187:9999
2019-12-12 12:21:11 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.88.4.153:8080
2019-12-12 12:21:11 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 1.20.97.96:54205
2019-12-12 12:21:12 connectionpool.py [line:437] DEBUG: http://183.88.4.153:8080 "GET http://httpbin.org/get HTTP/1.1" 200 530
2019-12-12 12:21:12 connectionpool.py [line:437] DEBUG: http://183.89.44.235:8080 "GET http://httpbin.org/get HTTP/1.1" 200 483
2019-12-12 12:21:12 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.70.192.130:8080
2019-12-12 12:21:12 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:12 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:13 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 43.245.202.110:58684
2019-12-12 12:21:14 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:15 connectionpool.py [line:437] DEBUG: http://117.252.67.206:8080 "GET http://httpbin.org/get HTTP/1.1" 200 560
2019-12-12 12:21:15 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:15 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.253.70.58:8080
2019-12-12 12:21:15 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.241.227.110:6666
2019-12-12 12:21:15 connectionpool.py [line:437] DEBUG: http://103.92.212.65:43399 "GET http://httpbin.org/get HTTP/1.1" 200 305
2019-12-12 12:21:15 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.108.201.18:83
2019-12-12 12:21:16 connectionpool.py [line:437] DEBUG: http://43.245.202.110:58684 "GET http://httpbin.org/get HTTP/1.1" 200 314
2019-12-12 12:21:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 139.0.157.24:8080
2019-12-12 12:21:17 connectionpool.py [line:437] DEBUG: http://45.70.192.130:8080 "GET http://httpbin.org/get HTTP/1.1" 200 503
2019-12-12 12:21:17 connectionpool.py [line:437] DEBUG: http://182.253.70.58:8080 "GET http://httpbin.org/get HTTP/1.1" 200 583
2019-12-12 12:21:17 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:17 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:19 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 49.0.39.186:8080
2019-12-12 12:21:19 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 14.207.197.42:8213
2019-12-12 12:21:20 connectionpool.py [line:437] DEBUG: http://139.0.157.24:8080 "GET http://httpbin.org/get HTTP/1.1" 200 532
2019-12-12 12:21:20 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:20 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:20 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.21.251:9999
2019-12-12 12:21:21 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.255.87.253:83
2019-12-12 12:21:21 connectionpool.py [line:437] DEBUG: http://223.198.21.251:9999 "GET http://httpbin.org/get HTTP/1.1" 403 3747
2019-12-12 12:21:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:21 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.121.43.79:9999
2019-12-12 12:21:21 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 196.216.215.29:56975
2019-12-12 12:21:22 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.112.130.34:31094
2019-12-12 12:21:22 connectionpool.py [line:437] DEBUG: http://36.255.87.253:83 "GET http://httpbin.org/get HTTP/1.1" 200 278
2019-12-12 12:21:22 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 186.219.213.86:60446
2019-12-12 12:21:23 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:25 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.80.238.197:53281
2019-12-12 12:21:25 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:25 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:25 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 185.209.240.24:8080
2019-12-12 12:21:26 connectionpool.py [line:437] DEBUG: http://49.0.39.186:8080 "GET http://httpbin.org/get HTTP/1.1" 200 485
2019-12-12 12:21:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:27 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:27 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:27 connectionpool.py [line:437] DEBUG: http://103.80.238.197:53281 "GET http://httpbin.org/get HTTP/1.1" 200 313
2019-12-12 12:21:28 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:28 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 138.99.109.22:37188
2019-12-12 12:21:29 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.56.107.244:48458
2019-12-12 12:21:30 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.37.114.42:41454
2019-12-12 12:21:30 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 202.93.228.150:39081
2019-12-12 12:21:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 196.20.12.49:8080
2019-12-12 12:21:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 80.84.57.227:80
2019-12-12 12:21:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.22.74:9999
2019-12-12 12:21:32 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 91.197.132.88:53281
2019-12-12 12:21:33 connectionpool.py [line:437] DEBUG: http://80.84.57.227:80 "GET http://httpbin.org/get HTTP/1.1" 200 315
2019-12-12 12:21:33 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:33 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.243.30.169:9999
2019-12-12 12:21:33 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.35.82.250:9999
2019-12-12 12:21:33 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:34 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.163.27.196:9999
2019-12-12 12:21:35 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:35 connectionpool.py [line:437] DEBUG: http://123.163.27.196:9999 "GET http://httpbin.org/get HTTP/1.1" 200 374
2019-12-12 12:21:35 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:35 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.166.163.146:9999
2019-12-12 12:21:35 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.248.133.253:9999
2019-12-12 12:21:36 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:38 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:38 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:38 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.243.27.44:9999
2019-12-12 12:21:39 connectionpool.py [line:437] DEBUG: http://36.37.114.42:41454 "GET http://httpbin.org/get HTTP/1.1" 200 317
2019-12-12 12:21:39 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.246.62:9999
2019-12-12 12:21:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.177.73:3000
2019-12-12 12:21:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.152.90.157:9999
2019-12-12 12:21:41 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 49.70.89.173:9999
2019-12-12 12:21:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.226.163.181:9999
2019-12-12 12:21:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.35.86.52:9999
2019-12-12 12:21:43 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:46 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:47 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:21:47 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 59.57.149.60:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 180.122.180.236:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.152.91.1:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 106.92.96.203:8118
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 175.44.108.113:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 171.35.162.52:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.16.26:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.22.243:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 190.206.123.169:8080
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.215.247.97:9999
2019-12-12 12:25:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 47.98.56.88:80
2019-12-12 12:25:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.20.227:9999
2019-12-12 12:25:40 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 122.2.37.38:34817
2019-12-12 12:25:40 connectionpool.py [line:437] DEBUG: http://47.98.56.88:80 "GET http://httpbin.org/get HTTP/1.1" 403 597
2019-12-12 12:25:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.195.170.175:9999
2019-12-12 12:25:41 connectionpool.py [line:437] DEBUG: http://223.198.20.227:9999 "GET http://httpbin.org/get HTTP/1.1" 200 305
2019-12-12 12:25:41 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.176.210:3000
2019-12-12 12:25:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 39.108.230.67:8080
2019-12-12 12:25:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:42 connectionpool.py [line:437] DEBUG: http://39.108.230.67:8080 "GET http://httpbin.org/get HTTP/1.1" 200 304
2019-12-12 12:25:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 218.2.226.42:80
2019-12-12 12:25:43 connectionpool.py [line:437] DEBUG: http://113.195.170.175:9999 "GET http://httpbin.org/get HTTP/1.1" 200 342
2019-12-12 12:25:43 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:43 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.209.131.3:8080
2019-12-12 12:25:43 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 1.199.31.25:9999
2019-12-12 12:25:43 connectionpool.py [line:437] DEBUG: http://59.57.149.60:9999 "GET http://httpbin.org/get HTTP/1.1" 200 336
2019-12-12 12:25:43 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:44 connectionpool.py [line:437] DEBUG: http://190.206.123.169:8080 "GET http://httpbin.org/get HTTP/1.1" 200 475
2019-12-12 12:25:44 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:437] DEBUG: http://218.2.226.42:80 "GET http://httpbin.org/get HTTP/1.1" 200 342
2019-12-12 12:25:45 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:45 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.44.122.85:8080
2019-12-12 12:25:46 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:46 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 81.190.208.52:35922
2019-12-12 12:25:48 connectionpool.py [line:437] DEBUG: http://103.209.131.3:8080 "GET http://httpbin.org/get HTTP/1.1" 200 499
2019-12-12 12:25:48 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:48 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:49 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.92.18.179:8080
2019-12-12 12:25:50 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.45.172.224:8118
2019-12-12 12:25:50 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.220.145.3:80
2019-12-12 12:25:50 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 78.62.214.242:60678
2019-12-12 12:25:50 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:50 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.245.198.101:8080
2019-12-12 12:25:51 connectionpool.py [line:437] DEBUG: http://183.45.172.224:8118 "GET http://httpbin.org/get HTTP/1.1" 200 320
2019-12-12 12:25:51 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:51 connectionpool.py [line:437] DEBUG: http://183.220.145.3:80 "GET http://httpbin.org/get HTTP/1.1" 200 302
2019-12-12 12:25:51 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:51 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 85.196.147.146:31784
2019-12-12 12:25:52 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 81.24.91.231:41258
2019-12-12 12:25:52 connectionpool.py [line:437] DEBUG: http://81.190.208.52:35922 "GET http://httpbin.org/get HTTP/1.1" 200 332
2019-12-12 12:25:52 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.242.191:9999
2019-12-12 12:25:52 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:53 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 219.239.142.253:3128
2019-12-12 12:25:53 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:54 connectionpool.py [line:437] DEBUG: http://219.239.142.253:3128 "GET http://httpbin.org/get HTTP/1.1" 200 499
2019-12-12 12:25:54 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:54 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.243.126:9999
2019-12-12 12:25:55 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 212.156.55.34:8080
2019-12-12 12:25:56 connectionpool.py [line:437] DEBUG: http://103.245.198.101:8080 "GET http://httpbin.org/get HTTP/1.1" 200 475
2019-12-12 12:25:56 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:56 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 185.44.229.227:34930
2019-12-12 12:25:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:58 connectionpool.py [line:437] DEBUG: http://85.196.147.146:31784 "GET http://httpbin.org/get HTTP/1.1" 200 280
2019-12-12 12:25:58 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.92.194.49:8118
2019-12-12 12:25:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 218.59.193.14:43554
2019-12-12 12:25:59 connectionpool.py [line:437] DEBUG: http://182.92.194.49:8118 "GET http://httpbin.org/get HTTP/1.1" 503 None
2019-12-12 12:25:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:25:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 203.150.172.151:8080
2019-12-12 12:25:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 189.124.91.185:8080
2019-12-12 12:26:00 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:00 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.232.39.55:8080
2019-12-12 12:26:01 connectionpool.py [line:437] DEBUG: http://212.156.55.34:8080 "GET http://httpbin.org/get HTTP/1.1" 200 450
2019-12-12 12:26:01 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:01 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 118.173.233.31:59669
2019-12-12 12:26:01 connectionpool.py [line:437] DEBUG: http://203.150.172.151:8080 "GET http://httpbin.org/get HTTP/1.1" 200 545
2019-12-12 12:26:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.168.252.49:8080
2019-12-12 12:26:02 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.99.0.176:9999
2019-12-12 12:26:04 connectionpool.py [line:437] DEBUG: http://218.59.193.14:43554 "GET http://httpbin.org/get HTTP/1.1" 200 332
2019-12-12 12:26:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:05 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.235.99.114:30865
2019-12-12 12:26:05 connectionpool.py [line:437] DEBUG: http://45.232.39.55:8080 "GET http://httpbin.org/get HTTP/1.1" 200 499
2019-12-12 12:26:05 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:07 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:07 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 74.113.173.78:47208
2019-12-12 12:26:08 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:08 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:08 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.46.207.215:9999
2019-12-12 12:26:09 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 118.96.173.115:8080
2019-12-12 12:26:09 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:10 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 168.205.92.94:8080
2019-12-12 12:26:10 connectionpool.py [line:437] DEBUG: http://176.235.99.114:30865 "GET http://httpbin.org/get HTTP/1.1" 200 484
2019-12-12 12:26:10 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:11 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 134.35.198.130:8080
2019-12-12 12:26:11 connectionpool.py [line:437] DEBUG: http://168.205.92.94:8080 "GET http://httpbin.org/get HTTP/1.1" 503 3872
2019-12-12 12:26:11 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:12 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.36.111.9:61102
2019-12-12 12:26:12 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:13 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 125.25.32.173:8080
2019-12-12 12:26:13 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:14 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.17.207:9999
2019-12-12 12:26:14 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 171.35.166.183:9999
2019-12-12 12:26:14 connectionpool.py [line:437] DEBUG: http://223.198.17.207:9999 "GET http://httpbin.org/get HTTP/1.1" 200 351
2019-12-12 12:26:14 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:15 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 119.179.196.116:9999
2019-12-12 12:26:15 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:15 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.20.72:9999
2019-12-12 12:26:15 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 120.55.69.176:8080
2019-12-12 12:26:15 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:16 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 190.5.118.42:8080
2019-12-12 12:26:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:16 connectionpool.py [line:437] DEBUG: http://125.25.32.173:8080 "GET http://httpbin.org/get HTTP/1.1" 200 503
2019-12-12 12:26:16 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:17 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:17 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.239.151.79:9999
2019-12-12 12:26:17 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:17 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 102.141.197.17:8080
2019-12-12 12:26:17 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 112.111.77.17:9999
2019-12-12 12:26:18 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.21.239:9999
2019-12-12 12:26:18 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.85.166.189:8118
2019-12-12 12:26:18 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:19 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:19 connectionpool.py [line:437] DEBUG: http://190.5.118.42:8080 "GET http://httpbin.org/get HTTP/1.1" 200 500
2019-12-12 12:26:20 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 195.178.33.86:8080
2019-12-12 12:26:20 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:20 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:20 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:21 connectionpool.py [line:437] DEBUG: http://223.198.21.239:9999 "GET http://httpbin.org/get HTTP/1.1" 200 345
2019-12-12 12:26:21 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:21 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 43.225.67.35:53905
2019-12-12 12:26:22 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:22 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.176.180:3000
2019-12-12 12:26:23 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.169.125.180:9999
2019-12-12 12:26:23 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.6.227.28:8080
2019-12-12 12:26:23 connectionpool.py [line:437] DEBUG: http://102.141.197.17:8080 "GET http://httpbin.org/get HTTP/1.1" 200 560
2019-12-12 12:26:24 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.166.163.178:9999
2019-12-12 12:26:25 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:25 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.63.205.248:30616
2019-12-12 12:26:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:26 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:27 connectionpool.py [line:437] DEBUG: http://114.6.227.28:8080 "GET http://httpbin.org/get HTTP/1.1" 200 307
2019-12-12 12:26:27 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:27 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:27 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 61.54.6.21:8118
2019-12-12 12:26:28 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:28 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:29 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:29 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:29 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.121.65.144:9999
2019-12-12 12:26:29 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.88.63.68:8080
2019-12-12 12:26:30 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 14.207.56.175:8080
2019-12-12 12:26:30 connectionpool.py [line:437] DEBUG: http://183.88.63.68:8080 "GET http://httpbin.org/get HTTP/1.1" 200 484
2019-12-12 12:26:30 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.89.44.235:8080
2019-12-12 12:26:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.92.212.65:43399
2019-12-12 12:26:31 connectionpool.py [line:437] DEBUG: http://14.207.56.175:8080 "GET http://httpbin.org/get HTTP/1.1" 200 497
2019-12-12 12:26:31 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:31 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.252.67.206:8080
2019-12-12 12:26:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 181.236.247.136:58310
2019-12-12 12:26:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.169.168.187:9999
2019-12-12 12:26:32 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.88.4.153:8080
2019-12-12 12:26:32 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:33 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 1.20.97.96:54205
2019-12-12 12:26:33 connectionpool.py [line:437] DEBUG: http://117.252.67.206:8080 "GET http://httpbin.org/get HTTP/1.1" 200 481
2019-12-12 12:26:33 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:33 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 45.70.192.130:8080
2019-12-12 12:26:34 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 43.245.202.110:58684
2019-12-12 12:26:34 connectionpool.py [line:437] DEBUG: http://183.88.4.153:8080 "GET http://httpbin.org/get HTTP/1.1" 200 461
2019-12-12 12:26:34 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.253.70.58:8080
2019-12-12 12:26:34 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:34 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:34 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:35 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.241.227.110:6666
2019-12-12 12:26:35 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.108.201.18:83
2019-12-12 12:26:36 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:37 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:38 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 139.0.157.24:8080
2019-12-12 12:26:38 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:39 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:39 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 49.0.39.186:8080
2019-12-12 12:26:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:40 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:41 connectionpool.py [line:437] DEBUG: http://182.253.70.58:8080 "GET http://httpbin.org/get HTTP/1.1" 200 499
2019-12-12 12:26:41 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:41 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 14.207.197.42:8213
2019-12-12 12:26:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.21.251:9999
2019-12-12 12:26:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.255.87.253:83
2019-12-12 12:26:42 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:42 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 113.121.43.79:9999
2019-12-12 12:26:44 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 196.216.215.29:56975
2019-12-12 12:26:44 connectionpool.py [line:437] DEBUG: http://36.255.87.253:83 "GET http://httpbin.org/get HTTP/1.1" 200 318
2019-12-12 12:26:44 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:45 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.112.130.34:31094
2019-12-12 12:26:45 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 186.219.213.86:60446
2019-12-12 12:26:45 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 103.80.238.197:53281
2019-12-12 12:26:46 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 185.209.240.24:8080
2019-12-12 12:26:46 connectionpool.py [line:437] DEBUG: http://139.0.157.24:8080 "GET http://httpbin.org/get HTTP/1.1" 200 570
2019-12-12 12:26:46 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:47 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 138.99.109.22:37188
2019-12-12 12:26:47 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:48 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:48 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:49 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:50 connectionpool.py [line:437] DEBUG: http://186.219.213.86:60446 "GET http://httpbin.org/get HTTP/1.1" 200 315
2019-12-12 12:26:50 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:50 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:51 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 176.56.107.244:48458
2019-12-12 12:26:51 connectionpool.py [line:437] DEBUG: http://185.209.240.24:8080 "GET http://httpbin.org/get HTTP/1.1" 200 319
2019-12-12 12:26:52 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.37.114.42:41454
2019-12-12 12:26:52 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:52 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 202.93.228.150:39081
2019-12-12 12:26:52 connectionpool.py [line:437] DEBUG: http://103.80.238.197:53281 "GET http://httpbin.org/get HTTP/1.1" 200 320
2019-12-12 12:26:53 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:54 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 196.20.12.49:8080
2019-12-12 12:26:54 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 80.84.57.227:80
2019-12-12 12:26:54 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:54 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 223.198.22.74:9999
2019-12-12 12:26:55 connectionpool.py [line:437] DEBUG: http://223.198.22.74:9999 "GET http://httpbin.org/get HTTP/1.1" 200 343
2019-12-12 12:26:55 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 91.197.132.88:53281
2019-12-12 12:26:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.243.30.169:9999
2019-12-12 12:26:55 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.35.82.250:9999
2019-12-12 12:26:56 connectionpool.py [line:437] DEBUG: http://80.84.57.227:80 "GET http://httpbin.org/get HTTP/1.1" 200 313
2019-12-12 12:26:56 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:437] DEBUG: http://91.197.132.88:53281 "GET http://httpbin.org/get HTTP/1.1" 200 335
2019-12-12 12:26:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 123.163.27.196:9999
2019-12-12 12:26:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 183.166.163.146:9999
2019-12-12 12:26:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:57 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 36.248.133.253:9999
2019-12-12 12:26:58 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 110.243.27.44:9999
2019-12-12 12:26:58 connectionpool.py [line:437] DEBUG: http://176.56.107.244:48458 "GET http://httpbin.org/get HTTP/1.1" 200 316
2019-12-12 12:26:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:59 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:26:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 163.204.246.62:9999
2019-12-12 12:26:59 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 117.88.177.73:3000
2019-12-12 12:27:00 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:00 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 27.152.90.157:9999
2019-12-12 12:27:02 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 49.70.89.173:9999
2019-12-12 12:27:02 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 114.226.163.181:9999
2019-12-12 12:27:02 connectionpool.py [line:225] DEBUG: Starting new HTTP connection (1): 182.35.86.52:9999
2019-12-12 12:27:02 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:03 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:04 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:07 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 12:27:07 connectionpool.py [line:959] DEBUG: Starting new HTTPS connection (1): httpbin.org:443
2019-12-12 13:58:52 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:6688/ (Press CTRL+C to quit)
2019-12-12 13:58:56 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:58:56] "GET / HTTP/1.1" 404 -
2019-12-12 13:58:56 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:58:56] "GET /favicon.ico HTTP/1.1" 404 -
2019-12-12 13:59:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:59:04] "GET / HTTP/1.1" 404 -
2019-12-12 13:59:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:59:04] "GET /favicon.ico HTTP/1.1" 404 -
2019-12-12 13:59:11 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol, domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 13:59:11 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:59:11] "GET /random HTTP/1.1" 500 -
2019-12-12 13:59:16 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol, domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 13:59:16 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 13:59:16] "GET /random HTTP/1.1" 500 -
2019-12-12 14:00:03 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:00:03] "GET /random/protocol=http HTTP/1.1" 404 -
2019-12-12 14:01:27 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:6688/ (Press CTRL+C to quit)
2019-12-12 14:01:39 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 14:01:45 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:01:45] "GET /random/protocol=http HTTP/1.1" 404 -
2019-12-12 14:01:45 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:01:45] "GET /favicon.ico HTTP/1.1" 404 -
2019-12-12 14:01:52 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol, domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 14:01:52 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:01:52] "GET /random HTTP/1.1" 500 -
2019-12-12 14:05:38 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 14:05:40 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:05:40] "GET / HTTP/1.1" 404 -
2019-12-12 14:05:40 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:05:40] "GET /favicon.ico HTTP/1.1" 404 -
2019-12-12 14:05:46 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 14:05:46 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 14:05:46] "GET /random HTTP/1.1" 500 -
2019-12-12 15:57:29 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 15:57:31 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 15:58:18 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 15:58:18 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 15:58:18] "GET /random?protocol=http HTTP/1.1" 500 -
2019-12-12 16:06:57 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:07:01 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:07:01 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:07:01] "GET /random?protocol=http HTTP/1.1" 500 -
2019-12-12 16:07:04 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:07:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:07:04] "GET /random?protocol=http HTTP/1.1" 500 -
2019-12-12 16:08:06 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 24, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 132, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:08:06 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:06] "GET /random?protocol=http HTTP/1.1" 500 -
2019-12-12 16:08:19 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:08:22 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:22] "GET /random?protocol=http HTTP/1.1" 200 -
2019-12-12 16:08:26 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:26] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:30 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:30] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:34 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:34] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:35 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:35] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:36 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:36] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:36 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:36] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:08:37 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:08:37] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:13:26 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:13:29 app.py [line:1891] ERROR: Exception on /random [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 27, in random
    raise e
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 25, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 136, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:13:29 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:13:29] "GET /random?protocol=https HTTP/1.1" 500 -
2019-12-12 16:16:44 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:16:47 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:16:47] "GET /random?protocol=https HTTP/1.1" 200 -
2019-12-12 16:16:59 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:16:59] "GET /random?protocol=https&nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:17:02 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:17:02] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:17:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:17:04] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:17:39 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:17:39] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:17:57 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:17:59 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:17:59] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:18:58 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:18:58] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:19:01 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:19:01] "GET /random?protocol=https&nick_type=0 HTTP/1.1" 200 -
2019-12-12 16:19:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:19:04] "GET /random?protocol=https&nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:19:45 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:19:50 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:19:50] "GET /random?protocol=https&nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:19:53 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:19:53] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:20:00 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:20:00] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:20:07 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:20:07] "GET /random?protocol=http HTTP/1.1" 200 -
2019-12-12 16:21:17 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:21:22 proxy_api.py [line:30] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 28, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:21:22 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:21:22] "GET /random?protocol=http HTTP/1.1" 200 -
2019-12-12 16:21:30 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:21:30] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:21:34 proxy_api.py [line:30] ERROR: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 28, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 136, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:21:34 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:21:34] "GET /random?protocol=http&nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:21:36 proxy_api.py [line:30] ERROR: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 28, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 136, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:21:36 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:21:36] "GET /random?protocol=http&nick_type=0 HTTP/1.1" 200 -
2019-12-12 16:22:29 proxy_api.py [line:30] ERROR: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 28, in random
    proxy = self.mongo_pool.random_proxy(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
  File "/Users/yjp/Desktop/IPProxyPool/core/db/mongo_pool.py", line 136, in random_proxy
    return random.choice(proxy_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-12-12 16:22:29 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:29] "GET /random?protocol=http&nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:22:32 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:32] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:22:35 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:35] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:22:36 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:36] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:22:37 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:37] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:22:37 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:22:37] "GET /random?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:35:00 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:35:07 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol, domain, nick_type, count=PROXIES_MAX_COUNT)
TypeError: get_proxies() got multiple values for argument 'count'
2019-12-12 16:35:07 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:35:07] "GET /proxies?protocol=http&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:35:14 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol, domain, nick_type, count=PROXIES_MAX_COUNT)
TypeError: get_proxies() got multiple values for argument 'count'
2019-12-12 16:35:14 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:35:14] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:36:49 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:36:52 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol, domain, nick_type, count=PROXIES_MAX_COUNT)
TypeError: get_proxies() got multiple values for argument 'count'
2019-12-12 16:36:52 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:36:52] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:37:13 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:37:16 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol, domain, nick_type, count=20)
TypeError: get_proxies() got multiple values for argument 'count'
2019-12-12 16:37:16 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:37:16] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:38:57 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:39:00 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:39:00] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:39:38 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:39:46 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 53, in proxies
    return json.dumps(proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Proxy' is not JSON serializable
2019-12-12 16:39:46 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:39:46] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:40:38 app.py [line:1891] ERROR: Exception on /proxies [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 53, in proxies
    return json.dumps(proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Proxy' is not JSON serializable
2019-12-12 16:40:38 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:40:38] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 500 -
2019-12-12 16:40:42 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:40:46 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:40:46] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:46:09 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:46:13 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:46:13] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:46:19 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:46:19] "GET /random?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:46:58 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:46:58] "GET /disable?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 404 -
2019-12-12 16:49:01 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:49:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:49:04] "GET /disable?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 404 -
2019-12-12 16:49:05 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:49:05] "GET /disable?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 404 -
2019-12-12 16:49:29 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:49:31 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:49:31] "GET /disable?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 404 -
2019-12-12 16:49:33 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:49:33] "GET /disable?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 404 -
2019-12-12 16:49:59 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:49:59] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:50:22 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:50:25 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:50:25] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:01 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:52:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:04] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:07 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:07] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:07 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:07] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:09 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:09] "GET /disable_domain?ip=192.168.0.1&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:17 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:17] "GET /disable_domain?ip=192.168.0.2&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:19 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:19] "GET /disable_domain?ip=192.168.0.2&domain=taobao.com HTTP/1.1" 200 -
2019-12-12 16:52:29 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:29] "GET /disable_domain?ip=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:52:37 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:52:37] "GET /disable_domain?domain=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:53:01 _internal.py [line:122] INFO:  * Running on http://0.0.0.0:16688/ (Press CTRL+C to quit)
2019-12-12 16:53:04 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:04] "GET /disable_domain?domain=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:53:09 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:09] "GET /disable_domain?ip=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:53:11 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:11] "GET /disable_domain?ip=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:53:44 proxy_api.py [line:53] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:53:44 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:44] "GET /proxies?ip=192.168.0.2 HTTP/1.1" 200 -
2019-12-12 16:53:47 proxy_api.py [line:53] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:53:47 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:47] "GET /proxies HTTP/1.1" 200 -
2019-12-12 16:53:52 proxy_api.py [line:53] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:53:52 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:52] "GET /proxies HTTP/1.1" 200 -
2019-12-12 16:53:58 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:53:58] "GET /proxies?protocol=https&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:54:09 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:09] "GET /proxies?protocol=http&nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:54:21 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:21] "GET /proxies?nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:54:24 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:24] "GET /proxies?nick_type=1 HTTP/1.1" 200 -
2019-12-12 16:54:26 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:26] "GET /proxies?nick_type=2 HTTP/1.1" 200 -
2019-12-12 16:54:29 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:29] "GET /proxies?nick_type=0 HTTP/1.1" 200 -
2019-12-12 16:54:36 proxy_api.py [line:53] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:54:36 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:54:36] "GET /proxies HTTP/1.1" 200 -
2019-12-12 16:55:16 proxy_api.py [line:53] ERROR: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/yjp/Desktop/IPProxyPool/core/proxy_api.py", line 51, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, nick_type=int(nick_type), count=PROXIES_MAX_COUNT)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-12-12 16:55:16 _internal.py [line:122] INFO: 127.0.0.1 - - [12/Dec/2019 16:55:16] "GET /proxies HTTP/1.1" 200 -
